/* eslint-disable */
/**
 * Generated data model types.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.31.2
 * To regenerate, run `npx convex dev`
 */

import type { DataModelFromSchemaDefinition } from "convex/server";
import type schema from "../schema";

/**
 * The names of all your Convex tables.
 */
export type TableNames = keyof DataModel;

/**
 * The type of a document stored in Convex.
 */
export type Doc<TableName extends TableNames> = DataModel[TableName]["document"];

/**
 * An identifier for a document in Convex.
 */
export type Id<TableName extends TableNames> = DataModel[TableName]["document"]["_id"];

/**
 * The data model defined by your schema.
 */
export type DataModel = DataModelFromSchemaDefinition<typeof schema>;
