/* eslint-disable */
/**
 * Generated utilities for implementing server-side Convex query and mutation functions.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.31.2
 * To regenerate, run `npx convex dev`
 */

import {
  actionGeneric,
  httpActionGeneric,
  queryGeneric,
  mutationGeneric,
  internalActionGeneric,
  internalMutationGeneric,
  internalQueryGeneric,
} from "convex/server";

/**
 * Define a query in this Convex app's public API.
 */
export const query = queryGeneric;

/**
 * Define a mutation in this Convex app's public API.
 */
export const mutation = mutationGeneric;

/**
 * Define an action in this Convex app's public API.
 */
export const action = actionGeneric;

/**
 * Define an HTTP action.
 */
export const httpAction = httpActionGeneric;

/**
 * Define a query that is only accessible from other Convex functions.
 */
export const internalQuery = internalQueryGeneric;

/**
 * Define a mutation that is only accessible from other Convex functions.
 */
export const internalMutation = internalMutationGeneric;

/**
 * Define an action that is only accessible from other Convex functions.
 */
export const internalAction = internalActionGeneric;
