/* eslint-disable */
/**
 * Generated utilities for implementing server-side Convex query and mutation functions.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.31.2
 * To regenerate, run `npx convex dev`
 */

import {
  ActionBuilder,
  HttpActionBuilder,
  MutationBuilder,
  QueryBuilder,
  GenericActionCtx,
  GenericMutationCtx,
  GenericQueryCtx,
} from "convex/server";
import type { DataModel } from "./dataModel.d";

/**
 * Define a query in this Convex app's public API.
 */
export declare const query: QueryBuilder<DataModel, "public">;

/**
 * Define a mutation in this Convex app's public API.
 */
export declare const mutation: MutationBuilder<DataModel, "public">;

/**
 * Define an action in this Convex app's public API.
 */
export declare const action: ActionBuilder<DataModel, "public">;

/**
 * Define an HTTP action.
 */
export declare const httpAction: HttpActionBuilder;

/**
 * Define a query that is only accessible from other Convex functions.
 */
export declare const internalQuery: QueryBuilder<DataModel, "internal">;

/**
 * Define a mutation that is only accessible from other Convex functions.
 */
export declare const internalMutation: MutationBuilder<DataModel, "internal">;

/**
 * Define an action that is only accessible from other Convex functions.
 */
export declare const internalAction: ActionBuilder<DataModel, "internal">;

/**
 * A type alias for the context of public queries in this Convex app.
 */
export type QueryCtx = GenericQueryCtx<DataModel>;

/**
 * A type alias for the context of public mutations in this Convex app.
 */
export type MutationCtx = GenericMutationCtx<DataModel>;

/**
 * A type alias for the context of public actions in this Convex app.
 */
export type ActionCtx = GenericActionCtx<DataModel>;
